apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  POSTGRES_DB: "deeptalk"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "root"
  PGPASSWORD: "root"
